### PR TITLE
Update OwO.py

### PR DESCRIPTION
**Pull request by 0u44**
something...

### CODE REVIEW

**Comment by Ccode-lang** [comment]
Seems better than what I was doing for adding those.  I'll test this later, the write function is semi broken and crashes of a capital U from my testing.  Maybe that was just a fluke though.

**Comment by CPScript** [comment]
ok

**Comment by Ccode-lang** [comment]
Unended if statement on line 13

**Comment by Ccode-lang** [comment]
also remove the last comment

**Comment by Ccode-lang** [comment]
```
Traceback (most recent call last):
  File "/home/ccode/owo-test/OwO.py", line 10, in <module>
    if keyboard.is_pressed("!") or keyboard.is_preseed("?"):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/keyboard/__init__.py", line 417, in is_pressed
    steps = parse_hotkey(hotkey)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/keyboard/__init__.py", line 344, in parse_hotkey
    scan_codes = key_to_scan_codes(hotkey)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/keyboard/__init__.py", line 324, in key_to_scan_codes
    raise ValueError('Key {} is not mapped to any known key.'.format(repr(key)), e)
ValueError: ("Key '!' is not mapped to any known key.", None)
```

**Pull request closed without merging**
